
#https://github.com/4wekromi

CC = g++
STD = c++11
DIR_LIBS = -Llib
CXX = main.cpp
OBJS = main.o
BIN = main.exe

all:
	$(CC) -Wall -c $(CXX) -std=$(STD)
	$(CC) -s $(OBJS) -o $(BIN) $(DIR_LIBS) -lTextParse
